### ISSUE TITLE
[Feature Suggestion - Edit Code] Extract Function/Method

### ISSUE THREAD

**Issue by lrfbranco** [WickedChive/Matlab-Editor-Plugin#162]
Hi there!

Firstly, thank you for this great extension. I was wondering if you think it's feasible to implement something like the "Extract Function/Method" available in many IDE's like in Visual Studio. 

Users have requested this before but Mathworks doesn't seem very interested in making it happen:
https://www.mathworks.com/matlabcentral/answers/287811-is-it-not-possible-to-extract-a-function-from-code-in-matlab#

Please visit the link above for more information about this.

Thank you!

**Comment by lrfbranco** [comment]
It appears Matlab has this since 2021b version. Sorry!

**Comment by GavriYashar** [comment]
Hi,

I myself don't use this plugin any more since matlab is developing a new desktop and I don't want to be spending time on a (imo) deprecated UI based on Java.
